# Generated by Django 5.1.4 on 2025-02-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rectangle_example', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectangle',
            name='length',
        ),
        migrations.AddField(
            model_name='rectangle',
            name='height',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='rectangle',
            name='width',
            field=models.IntegerField(),
        ),
    ]
